# Generated by Django 2.1 on 2020-09-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200921_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='salutarium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Salutarium'),
        ),
    ]
