# Generated by Django 2.1 on 2020-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200921_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='era_name',
            field=models.BooleanField(choices=[(True, 'T'), (False, 'S')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit_direction',
            field=models.BooleanField(choices=[(True, 'North'), (False, 'South')], default=True, null=True),
        ),
    ]
