# Generated by Django 2.1 on 2020-10-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200928_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unit_direction',
        ),
    ]
