# Generated by Django 2.1 on 2020-10-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_unit_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='era_name',
        ),
    ]
