# Generated by Django 2.1 on 2020-10-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_era_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit_layer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
